import Quiz from "../models/Quiz.js";
import UserQuiz from "../models/User.js";
import mongoose from "mongoose";
import { generateMCQWithContext, generateTrueFalseWithContext } from "../services/aiQuestionGenerator.js";
import { resolveAdaptiveDifficulty } from "../services/knowledgeLevelService.js";
import logger from "../utils/logger.js";
import { sendSuccess, sendError, sendValidationError, sendNotFound } from "../utils/responseHelper.js";
import AppError from "../utils/AppError.js";

const ALLOWED_AI_DIFFICULTIES = /** @type {const} */ (["easy", "medium", "hard"]);
const ALLOWED_RESOLVE_MODES = /** @type {const} */ (["performance", "intelligent", "blended"]);
const ALLOWED_PERFORMANCE = /** @type {const} */ (["low", "medium", "high"]);

/**
 * Explicit body.difficulty wins. Otherwise same resolver as /api/adaptive (profile + optional session blend).
 */
async function resolveDifficultyForStandardGenerate(reqBody, userId, quiz) {
    const raw = reqBody?.difficulty;
    if (raw != null && raw !== "") {
        const d = String(raw).toLowerCase().trim();
        if (ALLOWED_AI_DIFFICULTIES.includes(d)) {
            return {
                difficulty: d,
                source: "explicit_body",
                difficultyMode: null,
                profile: null,
            };
        }
    }

    const dmRaw = String(reqBody?.difficultyMode || "").toLowerCase().trim();
    const difficultyMode = ALLOWED_RESOLVE_MODES.includes(dmRaw) ? dmRaw : "intelligent";

    const pRaw = String(reqBody?.performance || "").toLowerCase().trim();
    const performance = ALLOWED_PERFORMANCE.includes(pRaw) ? pRaw : "medium";

    if (!userId) {
        return {
            difficulty: "medium",
            source: "fallback_no_user",
            difficultyMode,
            profile: null,
        };
    }

    const resolved = await resolveAdaptiveDifficulty({ difficultyMode, performance }, userId, quiz);
    return {
        difficulty: resolved.difficulty,
        source: resolved.source,
        difficultyMode,
        profile: resolved.profile || null,
    };
}

// ✅ General MCQ Generator
export const generateQuizQuestions = async (req, res) => {
    logger.info(
        `Generating ${req.body.numQuestions} ${req.body.questionType} questions for quiz ${req.params.id} on topic "${req.body.topic}"`
    );
    try {
        const { topic, numQuestions, questionType = "mcq" } = req.body;
        const { id } = req.params;

        if (!topic || !numQuestions) {
            logger.warn("Missing topic or numQuestions for AI question generation");
            return sendValidationError(
                res,
                { topic: "Topic and number of questions are required" },
                "Topic and number of questions are required"
            );
        }

        if (!mongoose.Types.ObjectId.isValid(id)) {
            logger.warn(`Invalid quiz ID for AI question generation: ${id}`);
            return sendValidationError(res, { id: "Invalid quiz ID" }, "Invalid quiz ID");
        }

        const quiz = await Quiz.findById(id);
        if (!quiz) {
            logger.warn(`Quiz not found: ${id} for AI question generation`);
            return sendNotFound(res, "Quiz");
        }

        const userId = req.user?.id;
        const resolvedDiff = await resolveDifficultyForStandardGenerate(req.body, userId, quiz);
        const difficulty = resolvedDiff.difficulty;

        logger.info(
            `Standard AI generate quiz ${id}: difficulty=${difficulty} source=${resolvedDiff.source} mode=${resolvedDiff.difficultyMode ?? "n/a"}`
        );

        const existingTexts = quiz.questions.map((q) => q.question.trim());

        let finalQuestions;
        try {
            if (questionType === "mcq") {
                const { questions } = await generateMCQWithContext(
                    topic,
                    numQuestions,
                    difficulty,
                    existingTexts
                );
                finalQuestions = questions;
            } else if (questionType === "true_false") {
                const { questions } = await generateTrueFalseWithContext(
                    topic,
                    numQuestions,
                    difficulty,
                    existingTexts
                );
                finalQuestions = questions;
            } else {
                logger.warn(`Invalid question type for AI question generation: ${questionType}`);
                return sendValidationError(res, { questionType: "Invalid question type" }, "Invalid question type");
            }
        } catch (error) {
            logger.error("Error generating questions:", error.message);
            throw error;
        }

        if (!finalQuestions.length) {
            logger.warn("No new unique questions could be generated by AI");
            return sendError(
                res,
                "No new unique questions could be generated. The quiz may already have similar questions, or the AI failed to generate valid questions.",
                400
            );
        }

        const questionsToAdd = finalQuestions.slice(0, numQuestions);
        quiz.questions.push(...questionsToAdd);
        quiz.totalMarks = quiz.questions.length;
        quiz.passingMarks = Math.ceil(quiz.totalMarks / 2);
        quiz.duration = quiz.questions.length * 2;

        await quiz.save();
        const addedCount = questionsToAdd.length;
        logger.info(
            `Successfully added ${addedCount} new questions to quiz ${id} (requested: ${numQuestions}, generated: ${finalQuestions.length})`
        );
        return sendSuccess(
            res,
            {
                questions: questionsToAdd,
                requested: numQuestions,
                added: addedCount,
                usedDifficulty: difficulty,
                difficultySource: resolvedDiff.source,
                difficultyMode: resolvedDiff.difficultyMode,
                knowledgeProfile: resolvedDiff.profile || undefined,
            },
            `${addedCount} new questions added successfully${
                addedCount < numQuestions
                    ? ` (requested ${numQuestions}, but only ${addedCount} unique questions could be generated)`
                    : ""
            }`
        );
    } catch (err) {
        logger.error({ message: "Error generating AI questions", error: err.message, stack: err.stack });
        throw new AppError("Internal server error", 500);
    }
};

// ✅ Adaptive MCQ Generator (performance / intelligent / blended difficulty)
export const generateAdaptiveQuestions = async (req, res) => {
    const {
        performance = "medium",
        quizId,
        numQuestions = 5,
        difficultyMode = "performance",
    } = req.body;

    logger.info(
        `Generating ${numQuestions} adaptive questions for quiz ${quizId} mode=${difficultyMode} performance=${performance}`
    );
    try {
        const allowedModes = ["performance", "intelligent", "blended"];
        const mode = allowedModes.includes(difficultyMode) ? difficultyMode : "performance";

        const quiz = await Quiz.findById(quizId);
        if (!quiz) {
            logger.warn(`Quiz not found: ${quizId} for adaptive question generation`);
            return sendNotFound(res, "Quiz");
        }

        const topic = quiz.category;
        const userId = req.user?.id;
        const resolved = await resolveAdaptiveDifficulty({ difficultyMode: mode, performance }, userId, quiz);
        const difficulty = resolved.difficulty;

        const existingTexts = quiz.questions.map((q) => q.question.trim());

        let finalQuestions;
        try {
            const { questions } = await generateMCQWithContext(topic, numQuestions, difficulty, existingTexts);
            finalQuestions = questions;
        } catch (error) {
            logger.error("Error generating adaptive questions:", error.message);
            throw error;
        }

        if (!finalQuestions.length) {
            logger.warn("No new unique adaptive questions could be generated by AI after all attempts");
            return sendError(
                res,
                "No new unique adaptive questions could be generated. The quiz may already have similar questions, or the AI failed to generate valid questions.",
                400
            );
        }

        const questionsToAdd = finalQuestions.slice(0, numQuestions);
        quiz.questions.push(...questionsToAdd);
        quiz.totalMarks = quiz.questions.length;
        quiz.duration = quiz.questions.length * 2;
        quiz.passingMarks = Math.ceil(quiz.totalMarks / 2);

        await quiz.save();
        const addedCount = questionsToAdd.length;
        logger.info(
            `Successfully added ${addedCount} new adaptive questions to quiz ${quizId} (requested: ${numQuestions}, generated: ${finalQuestions.length})`
        );

        if (userId) {
            try {
                await UserQuiz.findByIdAndUpdate(userId, {
                    $push: {
                        performanceHistory: {
                            $each: [
                                {
                                    quizId,
                                    category: quiz.category || "general",
                                    difficulty,
                                    score: null,
                                    totalQuestions: addedCount,
                                    timeSpent: 0,
                                    date: new Date(),
                                },
                            ],
                            $slice: -80,
                        },
                    },
                    $set: {
                        "intelligence.adaptiveDifficulty": difficulty,
                        "intelligence.lastAnalyzed": new Date(),
                    },
                });
            } catch (userErr) {
                logger.warn({ message: "Could not update user knowledge snapshot", error: userErr.message });
            }
        }

        return sendSuccess(
            res,
            {
                questions: questionsToAdd,
                requested: numQuestions,
                added: addedCount,
                usedDifficulty: difficulty,
                difficultyMode: mode,
                effectiveDifficultyMode: resolved.source,
                difficultySource: resolved.source,
                knowledgeProfile: resolved.profile || undefined,
            },
            `${addedCount} adaptive questions added successfully${
                addedCount < numQuestions
                    ? ` (requested ${numQuestions}, but only ${addedCount} unique questions could be generated)`
                    : ""
            }`
        );
    } catch (err) {
        logger.error({
            message: "Error generating adaptive AI questions",
            error: err.message,
            stack: err.stack,
        });
        throw new AppError("Internal server error", 500);
    }
};
